### ISSUE TITLE
Question for code

### ISSUE THREAD

**Issue by huajianyibeijiu** [someone755/ddr3-controller#4]
“localparam	lpdiv_CCD	= lp_BL/2/2 - 1;	// WRITE-to-WRITE (actually just BL/2 in DDR CK)(CCD = CAS#-to-CAS# delay)”Why here minus one?

**Comment by someone755** [comment]
See https://github.com/someone755/ddr3-controller/blob/master/ddr3_x16_phy_cust.v#L1055 The timing parameters are used as set values for when rn_state_tmr reaches 0.

CCD is the duration of the read/write burst. 8 data beats mean 4 clock cycles in the memory chip's clock domain. This means 2 clock cycles in the controller's ("slow") clock domain. To count 2 cycles, rn_state_tmr must count from 1 down to 0.
